### PR TITLE
Add some communication between client and server

### PR DESCRIPTION
**Pull request by farhansolodev**

### CODE REVIEW

**Review by FarazzShaikh — COMMENTED** [review]
We must discuss the scope of multiplayer before merging this in. **Lets call tomorrow.**

**Comment by farhansolodev** [comment]
> We must discuss the scope of multiplayer before merging this in. **Lets call tomorrow.**

Get a discord lol, my phone is dead

**Comment by FarazzShaikh** [comment]
I am working on a basic model for multiplayer, i will push it to a new branch, you can then add to that once it is made final by the end of this week. After i upload a basic skeleton for networking you too will fin it easier to understand. I don't fully understand your code so i will not merge it into master right now as it will not integrate with the backend rewrite i'm doing.

**Comment by FarazzShaikh** [comment]
@farhansolodev I have added to the _**Start-Backend**_ branch, You can begin work on multiplayer using my code as a starting point. I have made sure to comment every line.

**Pull request closed without merging**
